// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlrDzyVE2vYkBlcJxtq6zBljD4kbk_uo',
    appId: '1:604444244306:web:44fc871a0643f9bc7ae28b',
    messagingSenderId: '604444244306',
    projectId: 'es-mambo-lasmi',
    authDomain: 'es-mambo-lasmi.firebaseapp.com',
    storageBucket: 'es-mambo-lasmi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYO0gIbmqcu5YyP_jEXh0gv6P32HGAQzA',
    appId: '1:604444244306:android:1d54129fc2ae08e17ae28b',
    messagingSenderId: '604444244306',
    projectId: 'es-mambo-lasmi',
    storageBucket: 'es-mambo-lasmi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6P9ATyGLGOS0tQYw-mnUcdTduZa-lR8',
    appId: '1:604444244306:ios:cbc7ea9d8b4e8bf67ae28b',
    messagingSenderId: '604444244306',
    projectId: 'es-mambo-lasmi',
    storageBucket: 'es-mambo-lasmi.firebasestorage.app',
    iosBundleId: 'com.example.esmambolasmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx6P9ATyGLGOS0tQYw-mnUcdTduZa-lR8',
    appId: '1:604444244306:ios:cbc7ea9d8b4e8bf67ae28b',
    messagingSenderId: '604444244306',
    projectId: 'es-mambo-lasmi',
    storageBucket: 'es-mambo-lasmi.firebasestorage.app',
    iosBundleId: 'com.example.esmambolasmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQlrDzyVE2vYkBlcJxtq6zBljD4kbk_uo',
    appId: '1:604444244306:web:8c2ac3a3d48c9f8d7ae28b',
    messagingSenderId: '604444244306',
    projectId: 'es-mambo-lasmi',
    authDomain: 'es-mambo-lasmi.firebaseapp.com',
    storageBucket: 'es-mambo-lasmi.firebasestorage.app',
  );
}
